version: '3.9'
services:
  frontend:
    build:
      context: ../../
      dockerfile: apps/frontend/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ../../apps/frontend:/app
    command: pnpm dev
  backend:
    build:
      context: ../../
      dockerfile: apps/backend/Dockerfile
    ports:
      - '3030:3030'
    environment:
      - NODE_ENV=development
    volumes:
      - ../../apps/backend:/app
    command: pnpm start
  go-service:
    build:
      context: ../../
      dockerfile: apps/go-service/Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ../../apps/go-service:/app
    command: go run main.go
  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    volumes:
      - ../../infra/db:/var/lib/postgresql/data
