name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Format check
        run: pnpm format:check
      - name: Build
        run: pnpm build
      - name: Test (Go)
        run: cd apps/go-service && go test -v
      - name: Test (all workspaces)
        run: pnpm test

  build-and-push:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - run: pnpm install --frozen-lockfile
      - run: docker compose -f infra/docker/docker-compose.yml build
      # 本番用イメージpush例（要DockerHub認証）
      # - run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      # - run: docker push <your-image>
